pagopa/hub-pa-api

- .devops/code-review-pipelines.yml
This PR proposes to add SonarQube quality control.
- Code Review pipeline to interact with SonarQube server
SonarQube in required for a better control of quality and technical debt
- Manually in Azure DevOps
> Ptt 27 ci pipeline

- .devops/deploy-pipelines.yml
- upload-payments/Dockerfile.deploy
This PR proposes to add two tasks to the deploy pipeline to push image to container registry and release it to an app service.
- New task do create the docker image of the JOB microservice
- New task to release it to app service
This change is required to set a process of continuous deployment
Manually in azure dev portal
> [PTT-91] Added pipeline tasks and docker file to deploy JOB microservice

- upload-payments/openapi/upload-payments.yaml
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/controller/UploadPaymentsController.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/entity/PaymentJob.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/mapping/ConvertUploadCsvModelToPaymentJob.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/mapping/ConvertUploadCsvModelToPaymentsModel.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/model/PaymentJobModel.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/model/PaymentOptionsModel.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/model/PaymentPositionModel.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/model/servicemanagement/TributeServiceModel.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/repository/PaymentJobRepository.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/service/PaymentJobService.java
- upload-payments/src/test/java/it/gov/pagopa/hubpa/uploadpayments/controller/UploadPaymentsControllerTest.java
- upload-payments/src/test/java/it/gov/pagopa/hubpa/uploadpayments/mock/PaymentJobMock.java
- upload-payments/src/test/java/it/gov/pagopa/hubpa/uploadpayments/mock/PaymentJobModelMock.java
- upload-payments/src/test/java/it/gov/pagopa/hubpa/uploadpayments/mock/TributeServiceModelMock.java
- upload-payments/src/test/java/it/gov/pagopa/hubpa/uploadpayments/service/UploadPaymentServiceTest.java
The creditor is identify by a fiscal code, so it's necessary update the endpoint for work with fiscal code instead of creditor id
Creditor id has been removed from
-Controller
-Service
-Mappers
-Entity
The endpoints must work with fiscal codes
-Manual Tests via Swagger
> Ptt 110 remove creditor ids for fiscal code

- .devops/deploy-pipelines.yml
- service-managment/Dockerfile.deploy
This PR proposes to add two tasks in deploy pipeline to deploy _service_ miroservice
- Add a task in deploy pipeline to build the image
- Add Dockerfile for deployment
- Add task tu push the image to app service
Continuous Deployment of _service_ microservice
-manual tests on azure portal
> [PTT-113] Add tasks in deploy pipeline for service microservice

- docker-compose.yml
- upload-payments/pom.xml
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/service/PaymentJobService.java
- upload-payments/src/main/resources/application.properties
Replaced the rabbitMq with the JMS Azure
-add the jms in the PaymentJobService
-application.properties
We must replace the rabbitMQ with the JMS Azure
no test was performed
> [PTT-114] add azure jms

- docker-compose.yml
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/service/PaymentJobService.java
- upload-payments/src/main/resources/application.properties
This PR proposes to fix environment to connect to Azure Service Bus
- Fix environment variables to connect to Azure Service Bus
This changes are needed to connect to Azure Service bus
Test against a remote service bus queue
> [PTT-120] Fix Environment to connect to Service Bus via JMS

- ente-creditore/pom.xml
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/EnteCreditoreMicroService.java
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/ente/EnteCreditoreController.java
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/iban/IbanController.java
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/pa/PaController.java
It's necessary add the Swagger API to the Ente Creditore microservice
-added in pom the swagger dependency
-Updated the spring start class application EnteCreditoreMicroService for manage swagger
-Update the controller EnteCreditoreController to add information for swagger
-Update the controller IbanController to add information for swagger
-Update the controller PaController to add information for swagger
It's necessary add the Swagger API
-Swagger UI
> [PTT-53] added swagger to ente-creditore microservice

- payments/src/main/java/it/gov/pagopa/hubpa/payments/entity/PaymentPosition.java
- queue-worker/pom.xml
- queue-worker/src/main/java/it/gov/pagopa/hubpa/qworker/QueueReceiveController.java
- queue-worker/src/main/java/it/gov/pagopa/hubpa/qworker/QworkerApplication.java
- queue-worker/src/main/java/it/gov/pagopa/hubpa/uploadpayments/model/BooleanResponseModel.java
- queue-worker/src/main/java/it/gov/pagopa/hubpa/uploadpayments/model/PaymentJobMinimalModel.java
- queue-worker/src/main/resources/application.properties
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/controller/UploadPaymentsController.java
This PR proposes to integrate the queue-workers microservice with the job and payiments microservices
Queue-workers microservice
-Update the QueueReceiveController for perform the call to the paymnets endpoint for write the csv into the DB and the job endpoint for write the execution of job
-Update the QworkerApplication for add the RestTemplate
-Update application.properties for add the base path of the 2 endpoints
-Add the new models PaymentJobMinimalModel and BooleanResponseModel
Payments microservice
-Update PaymentPosition for remove a wrong not null field properties
Job microservice
-Update the UploadPaymentsController for change the type of service from PATH to POST
This PR was need to integrate the Queue-workers with the service for write the csv file into the DB structure and for …
> Integration from queue-worker and payments/upload-payment microservices

- .devops/code-review-pipelines.yml
Add SoonarCloud configuration
Wait to merge we're finishing last configurations
Static analisys.
> Add sonarcloud config

- .devops/code-review-pipelines.yml
- ente-creditore/pom.xml
- payments/pom.xml
- queue-worker/pom.xml
- service-managment/pom.xml
- upload-payments/pom.xml
This PR proposes a fix to code review pipeline and pom files to send test reports (test execution and coverage) to sonar cloud
- Fix the SonarPrepare task in code review pipeline
- Add JACOCO plugin (JAva COde COverage) to pom files
This changes are required to improve quality checks based on test coverage
Manual test on Azure DevOps
> PTT-27 Send test reports to SonarCloud

- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/privacy/BooleanResponseDto.java
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/privacy/PrivacyController.java
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/privacy/PrivacyEntity.java
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/privacy/PrivacyRepository.java
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/privacy/PrivacyService.java
- ente-creditore/src/test/java/it/gov/pagopa/hubpa/api/ApiTest.java
This PR  proposes to add the endpoints for save the privacy consent and check if a RefP have accepte the privacy consent.
-Add a new endpoint for save the consent
-Add a new endpoint for check the acceptance the privacy consent
This endpoints are required to allow the RefP to accept the privacy so it can use the TariTefa platform
> Ptt 140 privacy statement

- ente-creditore/pom.xml
- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/annotation/validation/implement/FiscalCodeValidator.java
- payments/pom.xml
- queue-worker/pom.xml
- service-managment/pom.xml
- support/pom.xml
- support/src/main/java/it/gov/pagopa/hubpa/support/service/SupportService.java
- support/src/test/java/it/gov/pagopa/hubpa/support/controller/SupportControllerTest.java
- support/src/test/java/it/gov/pagopa/hubpa/support/service/MailServiceTest.java
- support/src/test/java/it/gov/pagopa/hubpa/support/service/SupportServiceTest.java
- upload-payments/pom.xml
Improvement quality code
-for each microservice, update pom.xml with org.jacoco version
Removed smell code from:
-FiscalCodeValidator
-MailServiceTest
-SupportControllerTest
-SupportService
-SupportServiceTest
Improvement quality code
-Suite of integration tests
> Ptt 143 fix smell code

- service-managment/src/main/java/it/gov/pagopa/hubpa/servicemanagement/config/DevCorsConfiguration.java
- service-managment/src/test/java/it/gov/pagopa/hubpa/servicemanagement/controller/ServiceManagementControllerTest.java
This PR is needed for remove cors policy in BE
-DevCorsConfiguration
-ServiceManagementControllerTest
This PR is needed for remove cors policy in BE
> [PTT-145] cors policy revision

- ente-creditore/src/main/java/it/gov/pagopa/hubpa/api/annotation/validation/implement/IvaCodeValidator.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/config/DevCorsConfiguration.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/controller/PaymentsControllerTest.java
- support/src/main/java/it/gov/pagopa/hubpa/support/config/DevCorsConfiguration.java
- support/src/test/java/it/gov/pagopa/hubpa/support/controller/SupportControllerTest.java
- upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/config/DevCorsConfiguration.java
- upload-payments/src/test/java/it/gov/pagopa/hubpa/uploadpayments/controller/UploadPaymentsControllerTest.java
This PR is need for remove the useless cors configuration
-DevCorsConfiguration
-IvaCodeValidator
-PaymentsControllerTest
-SupportControllerTest
-UploadPaymentsControllerTest
This PR is need for remove the useless cors configuration
> [PTT-147] cors policy revision

- payments/src/main/java/it/gov/pagopa/hubpa/payments/mapper/ConvertUploadCsvModelToPaymentsModel.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/controller/PaymentsControllerTest.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/mock/TributeServiceModelMock.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/mock/UploadCsvModelMock.java
Fix null pointer in payments/create if configurated tribute has only "pagamento in unica soluzione" without installments.
Installments are optional.
Unit and integration tests.
> [PTT-214] payments mapper converter

- payments/src/main/java/it/gov/pagopa/hubpa/payments/controller/PaymentsController.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/mapper/ConvertPaymentPositionToPaymentMinimalModel.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/model/PaymentMinimalModel.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/controller/PaymentsControllerTest.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/mock/PaymentMinimalModelMock.java
This PR is need for show in the FrontEnd the information of a possible duplicated
-ConvertPaymentPositionToPaymentMinimalModel
-PaymentMinimalModel
-PaymentsController
This PR is need for show in the FrontEnd the information of a possible duplicated
> Ptt 230 info duplicated payments

- payments/src/main/java/it/gov/pagopa/hubpa/payments/mapper/ConvertPaymentPositionDebitorToCsvPositionModel.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/model/CsvPositionModel.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/controller/PaymentsControllerTest.java
This PR is need for add the reason to the position list csv export
-ConvertPaymentPositionDebitorToCsvPositionModel
-CsvPositionModel
Is need for add the reason to the position list csv export
> [PTT-195] add reason to csv export

- payments/src/main/java/it/gov/pagopa/hubpa/payments/controller/PaymentsController.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/entity/PaymentPosition.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/model/PublishModel.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/service/PaymentService.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/controller/PaymentsControllerTest.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/mock/PublishModelMock.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/service/PaymentServiceTest.java
This PR is need for allow the Ref-P to publish the payments
-PaymentService
-PaymentsController
-PublishModel
-PaymentPosition
This PR is need for allow the Ref-P to publish the payments
> Ptt 235 payments publish

- payments/src/main/java/it/gov/pagopa/hubpa/payments/config/WebServicesConfig.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/endpoints/PartnerEndpoint.java
- fix web service config to generate correctly wsdl definition;
The goal of this PR is to fix wsdl generation and expose it to the following path:
- `partner/partner.wsdl`
- Run app locally and go to:
http://localhost:8085/partner/partner.wsdl
> [PPT-223] fix wsdl generation

- payments/src/main/java/it/gov/pagopa/hubpa/payments/controller/PaymentsController.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/controller/PaymentsControllerTest.java
This PR is need for set the file name of the csv export directly from the path of the call
-PaymentsController
This PR is need for set the file name of the csv export directly from the path of the call
> [PTT-197] retrive filename from the path

- payments/src/main/java/it/gov/pagopa/hubpa/payments/iuvgenerator/validation/IuvCodeValidationImpl.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/mapper/ConvertUploadCsvModelToPaymentsModel.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/controller/PaymentsControllerTest.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/service/PaymentServiceTest.java
This PR is need to improve the coverage of uncovered conditions
-ConvertUploadCsvModelToPaymentsModel
-IuvCodeValidationImpl
-PaymentServiceTest
-PaymentsControllerTest
Improve the coverage of uncovered conditions
> [PTT-251] resolve unconvered conditions

- payments/pom.xml
- payments/src/main/java/it/gov/pagopa/hubpa/payments/config/WebServicesConfiguration.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/endpoints/PartnerEndpoint.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/endpoints/validation/SoapFaultDefinitionExceptionResolver.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/endpoints/validation/SoapMessageDispatcher.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/endpoints/validation/SoapValidatingInterceptor.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/endpoints/validation/SoapValidationException.java
- payments/src/main/java/it/gov/pagopa/hubpa/payments/service/PartnerService.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/endpoint/PartnerEndpointTest.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/endpoint/PartnerXsdValidationTest.java
- payments/src/test/java/it/gov/pagopa/hubpa/payments/service/PartnerServiceTest.java
- payments/src/test/resources/application.properties
- payments/src/test/resources/xsd/paForNode.xsd
- new custom runtime Exception: `SoapValidationException`;
- new custom MessageDispatcherServlet in order to handle `SoapValidationException`: `SoapMessageDispatcher`;
- new Endpoint Interceptor to throw `SoapValidationException` with invalid request according to xsd;
The goal of this PR is to add xsd validation of the endpoint partner requests and centralize the error response.
- run test `PartnerXsdValidationTest`;
> [PPT-253] Xsd Validation for Partner Endpoint
